# Generated by Django 3.2.4 on 2021-06-18 08:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.IntegerField(default=-1)),
                ('name', models.CharField(max_length=32)),
                ('isComplete', models.BooleanField(default=False)),
                ('memo', models.CharField(max_length=256)),
                ('order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('orderBy', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=32)),
                ('deadline', models.IntegerField(default=-1)),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('isComplete', models.BooleanField(default=False)),
                ('todoNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='manageapp.project')),
            ],
        ),
    ]
